version: "3"


services:
  go_service:
    build: .
    container_name: 'go_service'
    ports:
      - "8000:8080"
    volumes:
      - ./src:/usr/src/app

  go_service_mysql:
    image: mysql:8.0.31
    container_name: 'go_service_mysql'
    command: mysqld --sql_mode="" --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "8181:3306"
    volumes:
    - ./data/mysql:/var/lib/mysql
    - ./logs/mysql:/var/log/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root